### ISSUE TITLE
[功能请求]death_message添加参数

### ISSUE THREAD

**Issue by DancingSnow0517** [HuajiMUR233/MoreAPIs#6]
请求添加一个参数，可以提供玩家id
像是
`def death_message(server: ServerInterface, death_message, name):`

**Comment by DancingSnow0517** [comment]
秋梨膏qwq

**Comment by HuajiMUR233** [comment]
对我来说可能有些难，因为。。。我re用的不太好啊啊啊啊啊啊啊 :-(

**Comment by HuajiMUR233** [comment]
尝试实现了下这个功能

**Comment by HuajiMUR233** [comment]
我相信我做的是有问题的((((((((((

**Comment by DancingSnow0517** [comment]
找群里大佬帮忙qwq

**Comment by HuajiMUR233** [comment]
你先试试，我还没debug

**Comment by DancingSnow0517** [comment]
很好，你的东西我看不懂（
py太烂了

**Comment by HuajiMUR233** [comment]
:((((((((((((((((((((((
那么这个issue的意义是啥呀（（（

**Comment by HuajiMUR233** [comment]
算了我改回去吧

**Comment by DancingSnow0517** [comment]
所以才叫"功能请求"qwq

**Comment by HuajiMUR233** [comment]
有需要，我才做
并且这个事件是用来解决1.x没有0.x的on_death_message的
然后0.x没有所以我就没做:)

**Comment by DancingSnow0517** [comment]
0.x有返回名字的
